#!/bin/bash
# ============================================================================
# SLURM Array Job for Hyperparameter Sweeps on Euler
# ============================================================================
# Reads TASK_NAME and SEQUENTIAL_PER_JOB_LIST from the sweep file metadata
# header (generated by generate_sweep.py).
#
# Usage:
#   python euler/generate_sweep.py --config euler/sweep_config.yaml --submit
#   (or manually: sbatch --array=0-2 euler/sweep_euler.sh)
# ============================================================================

#SBATCH -n 1
#SBATCH --cpus-per-task=3
#SBATCH --gpus=rtx_4090:1
#SBATCH --time=07:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --job-name="ur5e_sweep"
#SBATCH --output=logs/sweep_%A_%a.out
#SBATCH --error=logs/sweep_%A_%a.err

# --- PATHS ---
PROJECT_PATH="$SLURM_SUBMIT_DIR"
PROJECT_NAME=$(basename "$PROJECT_PATH")
SCRIPT_DIR="$SLURM_SUBMIT_DIR/euler"
# SWEEP_FILE must be provided by sbatch via --export=SWEEP_FILE=/path/to/file.
if [ -z "$SWEEP_FILE" ]; then
    echo "Error: SWEEP_FILE environment variable not set."
    echo "  generate_sweep.py should pass the file via: sbatch --export=SWEEP_FILE=..."
    exit 1
else
    echo "Using SWEEP_FILE from environment: $SWEEP_FILE"
fi

# UPDATE THIS PATH to where you uploaded your .sif file
SIF_PATH="/cluster/scratch/$USER/isaac_euler_salziegl.sif"

# --- Validate sweep file ---
if [ ! -f "$SWEEP_FILE" ]; then
    echo "Error: $SWEEP_FILE not found."
    echo "  Run: python euler/generate_sweep.py --config euler/<your_config>.yaml"
    exit 1
fi

# --- Read metadata from sweep file header ---
TASK_NAME=$(grep '^# META task_name=' "$SWEEP_FILE" | head -1 | cut -d'=' -f2-)
SEQUENTIAL_LIST_LINE=$(grep '^# META sequential_per_job_list=' "$SWEEP_FILE" | head -1 | cut -d'=' -f2-)

if [ -z "$TASK_NAME" ]; then
    echo "Error: No '# META task_name=...' found in $SWEEP_FILE"
    echo "  Regenerate with: python euler/generate_sweep.py --config euler/<your_config>.yaml"
    exit 1
fi

if [ -z "$SEQUENTIAL_LIST_LINE" ]; then
    echo "Error: No '# META sequential_per_job_list=...' found in $SWEEP_FILE"
    echo "  Regenerate with: python euler/generate_sweep.py --config euler/<your_config>.yaml"
    exit 1
fi

IFS=',' read -r -a SEQ_ARR <<< "$SEQUENTIAL_LIST_LINE"
SEQ_LEN=${#SEQ_ARR[@]}

if [ -z "$SLURM_ARRAY_TASK_ID" ]; then
    echo "Error: SLURM_ARRAY_TASK_ID is not set."
    exit 1
fi
if [ "$SLURM_ARRAY_TASK_ID" -ge "$SEQ_LEN" ]; then
    echo "Error: SLURM_ARRAY_TASK_ID ($SLURM_ARRAY_TASK_ID) out of range for sequential_per_job_list (length=$SEQ_LEN)."
    exit 1
fi

SEQUENTIAL_PER_JOB=${SEQ_ARR[$SLURM_ARRAY_TASK_ID]}

# --- Initialise Modules & Load Proxy ---
# Initialize module environment (required on Euler)
if [ -f /etc/profile.d/modules.sh ]; then
    source /etc/profile.d/modules.sh
fi

# Load proxy for internet access on compute nodes
module load eth_proxy

# Debug: print proxy variables
echo "Proxy variables after module load:"
echo "  http_proxy=$http_proxy"
echo "  https_proxy=$https_proxy"
echo "  HTTP_PROXY=$HTTP_PROXY"
echo "  HTTPS_PROXY=$HTTPS_PROXY"

# Export proxy variables (sometimes module load doesn't export properly)
export http_proxy=${http_proxy:-$HTTP_PROXY}
export https_proxy=${https_proxy:-$HTTPS_PROXY}
export ftp_proxy=${ftp_proxy:-$FTP_PROXY}
export NO_PROXY=$no_proxy

echo "After export:"
echo "  http_proxy=$http_proxy"
echo "  https_proxy=$https_proxy"

# --- WandB API Key ---
if [ -f "$HOME/.wandb_key" ]; then
    export WANDB_API_KEY=$(cat $HOME/.wandb_key)
else
    echo "Error: ~/.wandb_key not found!"
    exit 1
fi

# --- Compute run range ---
# Count only non-comment, non-empty lines (actual run entries)
TOTAL_RUNS=$(grep -cv '^#\|^$' "$SWEEP_FILE")

# Compute START and END indices by summing previous entries in SEQ_ARR.
START_IDX=0
for ((i=0;i<SLURM_ARRAY_TASK_ID;i++)); do
    START_IDX=$((START_IDX + SEQ_ARR[i]))
done
END_IDX=$((START_IDX + SEQUENTIAL_PER_JOB - 1))

# --- CACHE SETUP ---
JOB_CACHE="/cluster/scratch/$USER/isaac_cache/${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"

mkdir -p $JOB_CACHE/kit_cache $JOB_CACHE/kit_data $JOB_CACHE/ov $JOB_CACHE/pip \
         $JOB_CACHE/glcache $JOB_CACHE/computecache $JOB_CACHE/logs $JOB_CACHE/data \
         $JOB_CACHE/documents $JOB_CACHE/warp $JOB_CACHE/local_lib \
         $JOB_CACHE/wandb_cache $JOB_CACHE/wandb_config $JOB_CACHE/wandb_data

# Load Proxy (Required for internet access on compute nodes)
module load eth_proxy

echo "================================================================"
echo "SWEEP Job $SLURM_ARRAY_TASK_ID  (Array Job $SLURM_ARRAY_JOB_ID)"
echo "Task:       $TASK_NAME"
echo "Project:    $PROJECT_NAME"
echo "Container:  $SIF_PATH"
echo "Runs:       $START_IDX to $END_IDX  (of $TOTAL_RUNS total)"
echo "Started:    $(date)"
echo "================================================================"

# --- INSTALL PROJECT (once per job) ---
echo ""
echo "[Setup] Installing project in editable mode..."
apptainer exec --nv \
    -B $JOB_CACHE/pip:$HOME/.cache/pip:rw \
    -B $JOB_CACHE/local_lib:$HOME/.local:rw \
    -B $PROJECT_PATH:/workspace/isaaclab/$PROJECT_NAME:rw \
    --env http_proxy=$http_proxy \
    --env https_proxy=$https_proxy \
    --env ftp_proxy=$ftp_proxy \
    --env no_proxy=$no_proxy \
    $SIF_PATH \
    bash -c "/isaac-sim/python.sh -m pip install --user -e /workspace/isaaclab/$PROJECT_NAME/source/$PROJECT_NAME"

INSTALL_EXIT=$?
if [ $INSTALL_EXIT -ne 0 ]; then
    echo "[Setup] FATAL: pip install failed with exit code $INSTALL_EXIT"
    rm -rf $JOB_CACHE
    exit 1
fi
echo "[Setup] Installation complete."

# --- SEQUENTIAL RUNS ---
PASS=0
FAIL=0

# Read only non-comment lines into an array (preserves indexing)
mapfile -t RUN_LINES < <(grep -v '^#\|^$' "$SWEEP_FILE")

for RUN_IDX in $(seq $START_IDX $END_IDX); do
    # Skip if beyond total runs
    if [ $RUN_IDX -ge $TOTAL_RUNS ]; then
        echo ""
        echo "[Run $RUN_IDX] Skipping (index >= $TOTAL_RUNS)"
        continue
    fi

    # Read run config (format: run_name|hydra_overrides)
    LINE="${RUN_LINES[$RUN_IDX]}"
    RUN_NAME=$(echo "$LINE" | cut -d'|' -f1)
    HYDRA_OVERRIDES=$(echo "$LINE" | cut -d'|' -f2-)

    echo ""
    echo "----------------------------------------------------------------"
    echo "[Run $RUN_IDX] $RUN_NAME"
    echo "  Overrides: $HYDRA_OVERRIDES"
    echo "  Started:   $(date)"
    echo "----------------------------------------------------------------"

    apptainer exec --nv \
        -B $JOB_CACHE/kit_cache:/isaac-sim/kit/cache:rw \
        -B $JOB_CACHE/kit_data:/isaac-sim/kit/data:rw \
        -B $JOB_CACHE/ov:$HOME/.cache/ov:rw \
        -B $JOB_CACHE/pip:$HOME/.cache/pip:rw \
        -B $JOB_CACHE/warp:$HOME/.cache/warp:rw \
        -B $JOB_CACHE/local_lib:$HOME/.local:rw \
        -B $JOB_CACHE/glcache:$HOME/.cache/nvidia/GLCache:rw \
        -B $JOB_CACHE/computecache:$HOME/.nv/ComputeCache:rw \
        -B $JOB_CACHE/logs:$HOME/.nvidia-omniverse/logs:rw \
        -B $JOB_CACHE/data:$HOME/.local/share/ov/data:rw \
        -B $JOB_CACHE/documents:$HOME/Documents:rw \
        -B $JOB_CACHE/wandb_cache:$HOME/.cache/wandb:rw \
        -B $JOB_CACHE/wandb_config:$HOME/.config/wandb:rw \
        -B $JOB_CACHE/wandb_data:$PROJECT_PATH/wandb:rw \
        -B $PROJECT_PATH:/workspace/isaaclab/$PROJECT_NAME:rw \
        --env WANDB_API_KEY=$WANDB_API_KEY \
        --env WANDB_DIR=$PROJECT_PATH \
        --env WANDB_CACHE_DIR=$HOME/.cache/wandb \
        --env WANDB_CONFIG_DIR=$HOME/.config/wandb \
        --env http_proxy=$http_proxy \
        --env https_proxy=$https_proxy \
        --env ftp_proxy=$ftp_proxy \
        --env no_proxy=$no_proxy \
        $SIF_PATH \
        bash -c "
            echo 'Starting Training: $RUN_NAME'
            /isaac-sim/python.sh /workspace/isaaclab/$PROJECT_NAME/scripts/rsl_rl/train.py \
                --task=$TASK_NAME \
                --headless \
                --run_name=$RUN_NAME \
                $HYDRA_OVERRIDES
        "

    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        echo "[Run $RUN_IDX] FAILED (exit code $EXIT_CODE) at $(date)"
        echo "[Run $RUN_IDX] Continuing to next run..."
        FAIL=$((FAIL + 1))
    else
        echo "[Run $RUN_IDX] PASSED at $(date)"
        PASS=$((PASS + 1))
    fi
done

echo ""
echo "================================================================"
echo "SWEEP Job $SLURM_ARRAY_TASK_ID complete at $(date)"
echo "  Passed: $PASS   Failed: $FAIL"
echo "================================================================"

# Cleanup Cache
rm -rf $JOB_CACHE
